[package]
name = "my_todo_list"
version = "1.0.0"
authors = []

[addresses]
todolist_addr='f2d288a5567522fb2f22cf14d45a376f2a75fb5c48f95c3affaa257b1acaaf65'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
